      SUBROUTINE LOOP_CT_CALLS_1(P,NHEL,H,IC)
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NBORNAMPS
      PARAMETER (NBORNAMPS=4)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NCOMB
      PARAMETER (NCOMB=8)
      INTEGER    NLOOPS, NLOOPGROUPS, NCTAMPS
      PARAMETER (NLOOPS=138, NLOOPGROUPS=16, NCTAMPS=86)
      INTEGER    NWAVEFUNCS,NLOOPWAVEFUNCS
      PARAMETER (NWAVEFUNCS=10,NLOOPWAVEFUNCS=237)
      INTEGER MAXLWFSIZE
      PARAMETER (MAXLWFSIZE=4)
      INTEGER LOOPMAXCOEFS, VERTEXMAXCOEFS
      PARAMETER (LOOPMAXCOEFS=126, VERTEXMAXCOEFS=15)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      REAL*16     MP__ZERO
      PARAMETER (MP__ZERO=0.0E0_16)
C     These are constants related to the split orders
      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=2)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER H
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,K
      COMPLEX*16 COEFS(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)

      LOGICAL DUMMYFALSE
      DATA DUMMYFALSE/.FALSE./
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      INCLUDE 'mp_coupl.inc'

      INTEGER HELOFFSET
      INTEGER GOODHEL(NCOMB)
      LOGICAL GOODAMP(NSQUAREDSO,NLOOPGROUPS)
      COMMON/FILTERS/GOODAMP,GOODHEL,HELOFFSET

      LOGICAL CHECKPHASE
      LOGICAL HELDOUBLECHECKED
      COMMON/INIT/CHECKPHASE, HELDOUBLECHECKED

      INTEGER SQSO_TARGET
      COMMON/SOCHOICE/SQSO_TARGET

      LOGICAL UVCT_REQ_SO_DONE,MP_UVCT_REQ_SO_DONE,CT_REQ_SO_DONE
     $ ,MP_CT_REQ_SO_DONE,LOOP_REQ_SO_DONE,MP_LOOP_REQ_SO_DONE
     $ ,CTCALL_REQ_SO_DONE,FILTER_SO
      COMMON/SO_REQS/UVCT_REQ_SO_DONE,MP_UVCT_REQ_SO_DONE,CT_REQ_SO_DON
     $ E,MP_CT_REQ_SO_DONE,LOOP_REQ_SO_DONE,MP_LOOP_REQ_SO_DONE
     $ ,CTCALL_REQ_SO_DONE,FILTER_SO

      INTEGER I_SO
      COMMON/I_SO/I_SO
      INTEGER I_LIB
      COMMON/I_LIB/I_LIB

      COMPLEX*16 AMP(NBORNAMPS)
      COMMON/AMPS/AMP
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMMON/W/W

      COMPLEX*16 WL(MAXLWFSIZE,0:LOOPMAXCOEFS-1,MAXLWFSIZE,0:NLOOPWAVEF
     $ UNCS)
      COMPLEX*16 PL(0:3,0:NLOOPWAVEFUNCS)
      COMMON/WL/WL,PL

      COMPLEX*16 LOOPCOEFS(0:LOOPMAXCOEFS-1,NSQUAREDSO,NLOOPGROUPS)
      COMMON/LCOEFS/LOOPCOEFS

      COMPLEX*16 AMPL(3,NCTAMPS)
      COMMON/AMPL/AMPL

      COMPLEX*16 LOOPRES(3,NSQUAREDSO,NLOOPGROUPS)
      LOGICAL S(NSQUAREDSO,NLOOPGROUPS)
      COMMON/LOOPRES/LOOPRES,S
C     
C     ----------
C     BEGIN CODE
C     ----------

C     The target squared split order contribution is already reached
C      if true.
      IF (FILTER_SO.AND.CTCALL_REQ_SO_DONE) THEN
        GOTO 1001
      ENDIF

C     CutTools call for loop numbers 1,10,19,28,37,46,52,130,108,109,11
C     0,111,112,113
      CALL LOOP_2(5,8,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,1)
C     CutTools call for loop numbers 2,11,20,29,38,53,114,131,61,62,63,
C     115,116,117
      CALL LOOP_2(6,9,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,2)
C     CutTools call for loop numbers 3,4,12,13,21,22,30,31,39,40,57,104
C     ,132,133
      CALL LOOP_3(2,4,6,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),3,I_SO
     $ ,3)
C     CutTools call for loop numbers 5,14,23,32,41,64,70,134,118,119,12
C     0,121,122,123
      CALL LOOP_2(10,7,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,4)
C     CutTools call for loop numbers 6,7,15,16,24,25,33,34,42,43,74,88,
C     135,136
      CALL LOOP_3(1,4,10,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),3,I_SO
     $ ,5)
C     CutTools call for loop numbers 8,9,17,18,26,27,35,36,44,45,77,80,
C     137,138
      CALL LOOP_3(1,2,8,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),3,I_SO
     $ ,6)
C     CutTools call for loop numbers 47,48,49,67,68,69,95,96,97
      CALL LOOP_2_3(1,2,3,5,4,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,7)
C     CutTools call for loop numbers 50,105,106,107
      CALL LOOP_3(3,4,5,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),4,I_SO
     $ ,8)
C     CutTools call for loop numbers 51,58,59,60,92,93,94,124,125,126
      CALL LOOP_2_3(1,2,4,5,3,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,9)
C     CutTools call for loop numbers 65,54,55,56,98,99,100,127,128,129
      CALL LOOP_2_3(1,2,2,7,3,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,10)
C     CutTools call for loop numbers 66,101,102,103
      CALL LOOP_3(2,3,7,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),4,I_SO
     $ ,11)
C     CutTools call for loop numbers 75,71,72,73,81,82,83,89,90,91
      CALL LOOP_2_3(1,2,1,9,3,DCMPLX(ZERO),DCMPLX(ZERO),2,I_SO,12)
C     CutTools call for loop numbers 76,84,85,86
      CALL LOOP_3(1,3,9,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO),4,I_SO
     $ ,13)
C     CutTools call for loop numbers 78
      CALL LOOP_4(1,2,4,3,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO)
     $ ,DCMPLX(ZERO),5,I_SO,14)
C     CutTools call for loop numbers 79
      CALL LOOP_4(1,2,3,4,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO)
     $ ,DCMPLX(ZERO),5,I_SO,15)
C     CutTools call for loop numbers 87
      CALL LOOP_4(1,3,2,4,DCMPLX(ZERO),DCMPLX(ZERO),DCMPLX(ZERO)
     $ ,DCMPLX(ZERO),5,I_SO,16)
C     At this point, all reductions needed for (QCD=4), i.e. of split
C      order ID=0, are computed.
      IF(FILTER_SO.AND.SQSO_TARGET.EQ.1) GOTO 5000

      GOTO 1001
 5000 CONTINUE
      CTCALL_REQ_SO_DONE=.TRUE.
 1001 CONTINUE
      END

