name: start runner on cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the 3.4.0 branch
  push:
    branches: [ git_test ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    checklm3runnerstatus:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      strategy:
       matrix:
        runner: [lemaitre3, nic5]
      steps:
        - uses: actions/checkout@v2
        - name: setup ssh
          uses: ./.github/clustersetup
          with: 
           sshkey: ${{ secrets.CECI_KEY }}
        - name: wait that no runnner is running
          run: ssh ${{ matrix.runner }} srun --dependency=singleton -J runner_mg5amc -t 01:00 hostname

    startlm3runner:
    # The type of runner that the job will run on
      needs: checklm3runnerstatus 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: setup ssh
          uses: ./.github/clustersetup
          with: 
           sshkey: ${{ secrets.CECI_KEY }}
        - name: start runner 
          run: ssh lemaitre3 srun --dependency=singleton -t 1:00:00 -J runner_mg5amc ./actions-runner/run.sh || echo "runner terminated"


    getslurmid:
      needs: checklm3runnerstatus
      runs-on: lemaitre3
      outputs:
        output1: ${{ steps.step1.outputs.test }}
      steps:
       - id: step1
         run: echo "::set-output name=test::${SLURM_JOB_ID}"
    
        
    actualwork:
      runs-on: lemaitre3
      needs: checklm3runnerstatus 
      name: A job to say hello
      steps:
        - uses: actions/checkout@v2
        - id: foo
          uses: ./.github/unnitest
          with:
            who-to-greet: 'Mona the Octocat'
        - run: echo random-number ${{ steps.foo.outputs.random-number }}
          shell: bash


    stoplm3runner:
      runs-on: ubuntu-latest
      needs: [getslurmid,actualwork]
      if: always()
      steps:
       - run: echo ${{needs.getslurmid.outputs.output1}}
       - uses: actions/checkout@v2
       - name: setup ssh
         uses: ./.github/clustersetup
         with: 
           sshkey: ${{ secrets.CECI_KEY }}
       - name: stop runner
         run: ssh lemaitre3 scancel ${{needs.getslurmid.outputs.output1}}
    
